baseURL = "http://logof.h1n.ru"
languageCode = "ru-RU"
hasCJKLanguage = true
disqusShortname = ""
googleAnalytics = ""
title = "Blog коллекция"
copyright = ""
theme = "my-collect"

[params]
	preview = ""
	platform = ""
	publisher =""
	author = "Logof"
	info = "Any info about you"
	pirates = false
[[params.social]]
  name = "Github"
  weight = 1
  url = "https://github.com/gonapps"

[[params.social]]
  name = "Gitlab"
  weight = 2
  url = "https://gitlab.com/gonapps"

[[params.social]]
  name = "Website"
  weight = 3
  url = "https://gonapps.com"
