baseURL = "http://localhost:1313"
languageCode = "en-us"
hasCJKLanguage = true
disqusShortname = ""
googleAnalytics = ""
title = "Your site title"
copyright = ""
theme = "my-collect"

[params]
	preview = ""
	platform: ""
	publisher: ""
	author = "Logof"
	info = "Any info about you"
	
[[params.social]]
  name = "Github"
  weight = 1
  url = "https://github.com/gonapps"

[[params.social]]
  name = "Gitlab"
  weight = 2
  url = "https://gitlab.com/gonapps"

[[params.social]]
  name = "Website"
  weight = 3
  url = "https://gonapps.com"
